server:
  port: ${EMAIL_SERVICE_PORT:8082}

spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_STARTTLS:false}

email:
  from: ${MAIL_FROM:noreply@srm.pl}
  enabled: ${MAIL_ENABLED:true}
templates:
  regulations-url: https://rekolekcje.scj.pl/informacje-organizacyjne/
  info-url: https://rekolekcje.scj.pl/informacje-organizacyjne/
  contact-email: zgloszenia.rek@scj.pl
  contact-phone: "+48 602 439 696"
  logo-url: https://rekolekcje.scj.pl/beta/wp-content/uploads/logo3.png

logging:
  level:
    pl.srm.emailservice: DEBUG
